### ISSUE TITLE
Great job !

### ISSUE THREAD

**Issue by johnmackintosh** [NicolasRuth/metallicaR#1]
Hi Nicolas
I  just wanted to say well done on a great piece of analysis.  I particularly enjoyed the boxplots of song tempos, its really interesting to see that they are starting to get a bit faster again overall. 

I 've done some work on sentiment analysis of their lyrics, but I think looking into the qualities of their music is actually much more interesting. 
Once again, nice work and thanks for sharing 💯

**Comment by NicolasRuth** [comment]
Hey John, 
thank you very much! Tempo is really interesting seems like Death Magnetic was going back to the Thrash Metal tempo roots of Kill Em All.
You are welcome!
Cheers,
Nick
